version: '3.7'

services:
  register:
    image: momcilovicluka/anirest-register:latest
    mem_limit: 700m
    ports:
      - "6969:6969"
    networks:
      - anirest-network
    depends_on:
      - naming-server
      - config-server
      - db
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

  anime:
    image: momcilovicluka/anirest-anime:latest
    mem_limit: 700m    
    ports:
      - "1337:1337"
    networks:
      - anirest-network
    depends_on:
      - naming-server
      - config-server
      - db
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

  anime-list:
    image: momcilovicluka/anirest-anime-list:latest
    mem_limit: 700m
    ports:
      - "42000:42000"
    networks:
      - anirest-network
    depends_on:
      - naming-server
      - config-server
      - db
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

  tag:
    image: momcilovicluka/anirest-tag:latest
    mem_limit: 700m
    ports:
      - "38160:38160"
    networks:
      - anirest-network
    depends_on:
      - naming-server
      - config-server
      - db
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

  api-gateway:
    image: momcilovicluka/anirest-api-gateway:latest
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - anirest-network
    depends_on:
      - naming-server
      - db
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

  config-server:
    image: momcilovicluka/anirest-config-server:latest
    mem_limit: 700m
    ports:
      - "9001:9001"
    networks:
      - anirest-network
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka

  naming-server:
    image: momcilovicluka/anirest-naming-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - anirest-network
  
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime
      MAX_ALLOWED_PACKET: 1024M
    ports:
      - "3306:3306"
    networks:
      - anirest-network
    volumes:
      - ./Database/my.cnf:/etc/mysql/my.cnf
      - ./Database/dump.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      UPLOAD_LIMIT: 100M
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/anime
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - anirest-network

networks:
  anirest-network:
    driver: bridge
