-- MySQL Script generated by MySQL Workbench
-- Sat Jan  6 21:54:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Season`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Season` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Season` (
  `idSeason` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSeason`),
  UNIQUE INDEX `idSeason_UNIQUE` (`idSeason` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `idType` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `idType_UNIQUE` (`idType` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Format` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Format` (
  `idformat` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idformat`),
  UNIQUE INDEX `idformat_UNIQUE` (`idformat` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `idStatus` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatus`),
  UNIQUE INDEX `idStatus_UNIQUE` (`idStatus` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anime` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anime` (
  `idAnime` INT NOT NULL AUTO_INCREMENT,
  `idMal` INT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `Season_idSeason` INT NULL,
  `seasonYear` INT NULL,
  `Type_idType` INT NULL,
  `format_idFormat` INT NULL,
  `Status_idStatus` INT NULL,
  `episodes` INT NULL,
  `duration` INT NULL,
  `averageScore` INT NULL,
  `popularity` INT NULL,
  `title` VARCHAR(500) NOT NULL,
  `titleRomaji` VARCHAR(500) NULL,
  `titleNative` VARCHAR(500) NULL,
  PRIMARY KEY (`idAnime`),
  INDEX `fk_Anime_Season_idx` (`Season_idSeason` ASC) VISIBLE,
  INDEX `fk_Anime_Type1_idx` (`Type_idType` ASC) VISIBLE,
  UNIQUE INDEX `idAnime_UNIQUE` (`idAnime` ASC) VISIBLE,
  UNIQUE INDEX `idMal_UNIQUE` (`idMal` ASC) VISIBLE,
  INDEX `fk_Anime_format1_idx` (`format_idFormat` ASC) VISIBLE,
  INDEX `fk_Anime_Status1_idx` (`Status_idStatus` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_Season`
    FOREIGN KEY (`Season_idSeason`)
    REFERENCES `mydb`.`Season` (`idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_Type1`
    FOREIGN KEY (`Type_idType`)
    REFERENCES `mydb`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_format1`
    FOREIGN KEY (`format_idFormat`)
    REFERENCES `mydb`.`Format` (`idformat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_Status1`
    FOREIGN KEY (`Status_idStatus`)
    REFERENCES `mydb`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `idGenre` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGenre`),
  UNIQUE INDEX `idGenre_UNIQUE` (`idGenre` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anime_has_Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anime_has_Genre` (
  `Anime_idAnime` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Anime_idAnime`, `Genre_idGenre`),
  INDEX `fk_Anime_has_Genre_Genre1_idx` (`Genre_idGenre` ASC) VISIBLE,
  INDEX `fk_Anime_has_Genre_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Genre_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Genre_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `mydb`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `idTag` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `category` VARCHAR(100) NULL,
  `rank` INT NULL,
  `isGeneralSpoiler` TINYINT NULL,
  `isMediaSpoiler` TINYINT NULL,
  `isAdult` TINYINT NULL,
  `userId` INT NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `idTag_UNIQUE` (`idTag` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime_has_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anime_has_Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anime_has_Tag` (
  `Anime_idAnime` INT NOT NULL,
  `Tag_idTag` INT NOT NULL,
  PRIMARY KEY (`Anime_idAnime`, `Tag_idTag`),
  INDEX `fk_Anime_has_Tag_Tag1_idx` (`Tag_idTag` ASC) VISIBLE,
  INDEX `fk_Anime_has_Tag_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Tag_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Tag_Tag1`
    FOREIGN KEY (`Tag_idTag`)
    REFERENCES `mydb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Character` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Character` (
  `idCharacter` INT NOT NULL,
  `nameFirst` VARCHAR(100) NULL,
  `nameMiddle` VARCHAR(100) NULL,
  `nameLast` VARCHAR(100) NULL,
  `nameFull` VARCHAR(300) NOT NULL,
  `nameNative` VARCHAR(300) NULL,
  `nameAlternative` VARCHAR(500) NULL,
  `nameAlternativeSpoiler` VARCHAR(300) NULL,
  `image` BLOB NULL,
  `description` VARCHAR(1000) NULL,
  `gender` VARCHAR(100) NULL,
  `dateOfBirth` DATE NULL,
  `age` VARCHAR(500) NULL,
  `bloodType` VARCHAR(45) NULL,
  `siteUrl` VARCHAR(200) NULL,
  `favourites` INT NULL,
  PRIMARY KEY (`idCharacter`),
  UNIQUE INDEX `idCharacter_UNIQUE` (`idCharacter` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime_has_Character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anime_has_Character` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anime_has_Character` (
  `Anime_idAnime` INT NOT NULL,
  `Character_idCharacter` INT NOT NULL,
  PRIMARY KEY (`Anime_idAnime`, `Character_idCharacter`),
  INDEX `fk_Anime_has_Character_Character1_idx` (`Character_idCharacter` ASC) VISIBLE,
  INDEX `fk_Anime_has_Character_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Character_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Character_Character1`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `mydb`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `surname` VARCHAR(100) NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AnimeList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AnimeList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AnimeList` (
  `idAnimeList` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idAnimeList`),
  INDEX `fk_AnimeList_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_AnimeList_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AnimeList_has_Anime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AnimeList_has_Anime` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AnimeList_has_Anime` (
  `AnimeList_idAnimeList` INT NOT NULL,
  `Anime_idAnime` INT NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`AnimeList_idAnimeList`, `Anime_idAnime`),
  INDEX `fk_AnimeList_has_Anime_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  INDEX `fk_AnimeList_has_Anime_AnimeList1_idx` (`AnimeList_idAnimeList` ASC) VISIBLE,
  CONSTRAINT `fk_AnimeList_has_Anime_AnimeList1`
    FOREIGN KEY (`AnimeList_idAnimeList`)
    REFERENCES `mydb`.`AnimeList` (`idAnimeList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnimeList_has_Anime_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CharacterList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CharacterList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CharacterList` (
  `idCharacterList` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCharacterList`),
  INDEX `fk_CharacterList_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_CharacterList_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CharacterList_has_Character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CharacterList_has_Character` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CharacterList_has_Character` (
  `CharacterList_idCharacterList` INT NOT NULL,
  `Character_idCharacter` INT NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`CharacterList_idCharacterList`, `Character_idCharacter`),
  INDEX `fk_CharacterList_has_Character_Character1_idx` (`Character_idCharacter` ASC) VISIBLE,
  INDEX `fk_CharacterList_has_Character_CharacterList1_idx` (`CharacterList_idCharacterList` ASC) VISIBLE,
  CONSTRAINT `fk_CharacterList_has_Character_CharacterList1`
    FOREIGN KEY (`CharacterList_idCharacterList`)
    REFERENCES `mydb`.`CharacterList` (`idCharacterList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CharacterList_has_Character_Character1`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `mydb`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
